### ISSUE TITLE
Fix Meeting Times

### ISSUE THREAD

**Issue by Tech-Wizz** [MSURoboCats/website#60]
This needs to be updated. Also is there a way to have this auto-updated from a spreadsheet or note we can add to the website GitHub. This would make it easier and more simple to fix the issue.

**Comment by byfar94** [comment]
Hi Tech-Wizz, you can embed a google calendar or google sheets so that your team can easily edit meeting times from your google drive. I can do it for your, but you would need to provide me with the <iframe> html info google provides you. It's easy to get to, here's a link to a video on how to get it from google calendar https://www.youtube.com/watch?v=fqPXx03Rl2Y.

let me know if you're interested in doing it this way and I can help.

**Comment by Tech-Wizz** [comment]
We also need to add meeting locations
